#!/usr/bin/env bash
# neovim_themegen.sh — writes the LazyVim plugin spec for yukazakiri/ilmango.nvim.
# The plugin itself handles all colour fetching, highlights, and live reload.
#
# Usage: neovim_themegen.sh <palette.json> <terminal.json> <plugin_dir>
set -euo pipefail

PALETTE_FILE="${1:?Usage: $0 <palette.json> <terminal.json> <plugin_dir>}"
TERMINAL_FILE="${2:?}"
NEOVIM_PLUGIN_DIR="${3:?}"

NEOVIM_CONFIG_DIR="$(dirname "$(dirname "$NEOVIM_PLUGIN_DIR")")"

# Write file only if changed
write_if_changed() {
  local target="$1" tmp="${1}.tmp"
  cat > "$tmp"
  if [[ -f "$target" ]] && cmp -s "$tmp" "$target"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$target"
    printf '[neovim_themegen] %s updated\n' "$(basename "$target")"
  fi
}

mkdir -p "$NEOVIM_PLUGIN_DIR"
write_if_changed "$NEOVIM_PLUGIN_DIR/neovim.lua" <<'PLUGEOF'
-- neovim.lua — auto-generated by Illogical-mango. Use 99-ilmango-user.lua for overrides.
return {
  {
    "yukazakiri/ilmango.nvim",
    priority = 1000,
    opts = {},
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "ilmango",
    },
  },
}
PLUGEOF

# Clean up stale files from previous versions
for stale in \
  "$NEOVIM_PLUGIN_DIR/ilmango-colorscheme.lua" \
  "$NEOVIM_PLUGIN_DIR/ilmango_theme.lua" \
  "$NEOVIM_CONFIG_DIR/colors/ilmango.lua"
do
  if [[ -f "$stale" ]]; then
    rm -f "$stale"
    printf '[neovim_themegen] removed stale: %s\n' "$(basename "$stale")"
  fi
done
